# Audio recording settings
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 4096
  format: 'wav'
  duration: 10.0
  clipping_threshold: 0.95
  min_level_threshold: 0.1

# Dataset configuration
dataset:
  repo_id: "pauljunsukhan/throatmic_codered"
  metadata_file: "data/metadata/metadata.csv"
  recordings_dir: "data/recordings"
  dataset_card: "DATASET_CARD.md"
  min_words: 12
  max_words: 25
  min_duration: 8.0
  max_duration: 12.0

# Sentence filtering configuration
sentence_filter:
  min_chars: 60
  max_chars: 200
  min_words: 5
  max_words: 30
  max_entities: 3
  max_persons: 2
  max_locations: 1
  max_organizations: 2
  min_complexity_score: 2
  min_total_complexity: 3
  pos_ratios:
    VERB: [0.1, 0.35]
    NOUN: [0.2, 0.45]
    ADJ: [0.05, 0.25]

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "data/throatmic.log"