[project]
name = "throatmicdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dvc-s3==3.0.1",
    "dvc==3.38.1",
    "pyaudio==0.2.13",
    "requests==2.31.0",
    "sounddevice==0.4.6",
    "wave==0.0.2",
    "datasets==2.16.1",
    "huggingface-hub==0.20.3",
    "librosa==0.10.1",
    "tqdm==4.66.1",
]
